name: Jalankan Bot Hewan Joget

on:
  schedule:
    - cron: '0 1 * * *'   # setiap hari jam 01:00 UTC
  workflow_dispatch:      # biar bisa di-run manual dari GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
    - name: Jalankan bot
      env:
        FB_TOKEN: ${{ secrets.FB_TOKEN }}
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      run: python bot.py
