name: Monster V8 Ultra Force

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Bahan
      run: pip install cloudscraper beautifulsoup4 requests

    - name: Jalankan Bot
      # Perintah ini akan mencari file monster-v8-ultra.py di mana saja dia berada
      run: |
        FILE=$(find . -name "monster-v8-ultra.py" | head -n 1)
        python "$FILE"
